apiVersion: v1
kind: Secret
metadata:
  name: checkout-api-secrets
  namespace: checkout-system
type: Opaque
data:
  # postgresql://checkout_user:prod_password_here@postgres-service.checkout-system.svc.cluster.local:5432/checkout_prod
  DATABASE_URL: cG9zdGdyZXNxbDovL2NoZWNrb3V0X3VzZXI6cHJvZF9wYXNzd29yZF9oZXJlQHBvc3RncmVzLXNlcnZpY2UuY2hlY2tvdXQtc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvY2hlY2tvdXRfcHJvZA==
  # redis://:redis_prod_password@redis-service.checkout-system.svc.cluster.local:6379/0
  REDIS_URL: cmVkaXM6Ly86cmVkaXNfcHJvZF9wYXNzd29yZEByZWRpcy1zZXJ2aWNlLmNoZWNrb3V0LXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbDo2Mzc5LzA=
